version: '3.9'

services:
  app-test:
    container_name: webtronics-app-test
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "tail -f > /dev/null"
    ports:
      - '8000:8000'
    environment: 
      - PYTHONPATH=./src
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webtronics_test
      - POSTGRES_USER=webtronics_test
      - POSTGRES_HOST=db-test
      - REDIS_HOST=redis-test
      - REIDS_PORT=6379
    depends_on:
      - db-test
      - redis-test
    volumes:
      - ./migrations:/app/migrations
      - ./tests:/app/tests
      - ./src:/app/src

  db-test:
    container_name: webtronics-db-test
    image: postgres:15
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=webtronics_test
    restart: on-failure

  redis-test:
    container_name: webtronics-redis-test
    image: redis:latest
    ports:
      - '6379:6379'
    restart: on-failure
