version: '3.9'

services:
  app:
    container_name: webtronics-app-test
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "poetry run alembic upgrade heads && tail -f /dev/null"
    ports:
      - '8000:8000'
    env_file: .test.env
    environment: 
      - PYTHONPATH=./src
    depends_on:
      - db-test
      - redis-test

  db-test:
    container_name: webtronics-db-test
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file: .test.env
    restart: on-failure

  redis-test:
    container_name: webtronics-redis-test
    image: redis:latest
    ports:
      - '6379:6379'
    env_file: .test.env
    restart: on-failure

