version: '3.9'

services:
  app:
    container_name: webtronics-app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "poetry run alembic upgrade heads && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    env_file: .env
    environment: 
      - PYTHONPATH=./src
    depends_on:
      - db
      - redis
  db:
    container_name: webtronics-db
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file: .env
    restart: unless-stopped
  redis:
    container_name: webtronics-redis
    image: redis:latest
    ports:
      - '6379:6379'
    restart: unless-stopped
