version: '3.9'

services:
  app:
    container_name: webtronics-app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run alembic upgrade heads 
      && poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
